// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArCW4CY-nP2SDXY-jvs6BxkaGQ9usIZeU',
    appId: '1:544284971308:web:25f837291dc2af42495c89',
    messagingSenderId: '544284971308',
    projectId: 'airdrop-908a2',
    authDomain: 'airdrop-908a2.firebaseapp.com',
    storageBucket: 'airdrop-908a2.firebasestorage.app',
    measurementId: 'G-6Z472LQM4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcUPrkFMD3_UEiey6v6OWxLgVhYYdjzY',
    appId: '1:544284971308:android:8a08e6c30a13328a495c89',
    messagingSenderId: '544284971308',
    projectId: 'airdrop-908a2',
    storageBucket: 'airdrop-908a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpsb5ccUCSAUBhXTnwj53Sz3Bu0fNVCo',
    appId: '1:544284971308:ios:990c846d46afdff6495c89',
    messagingSenderId: '544284971308',
    projectId: 'airdrop-908a2',
    storageBucket: 'airdrop-908a2.firebasestorage.app',
    iosBundleId: 'com.example.airdropFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpsb5ccUCSAUBhXTnwj53Sz3Bu0fNVCo',
    appId: '1:544284971308:ios:990c846d46afdff6495c89',
    messagingSenderId: '544284971308',
    projectId: 'airdrop-908a2',
    storageBucket: 'airdrop-908a2.firebasestorage.app',
    iosBundleId: 'com.example.airdropFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArCW4CY-nP2SDXY-jvs6BxkaGQ9usIZeU',
    appId: '1:544284971308:web:76793785efc00003495c89',
    messagingSenderId: '544284971308',
    projectId: 'airdrop-908a2',
    authDomain: 'airdrop-908a2.firebaseapp.com',
    storageBucket: 'airdrop-908a2.firebasestorage.app',
    measurementId: 'G-KE4WF9X2JE',
  );
}
